In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
data_set = pd.read_csv('iris.csv')
data_set.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
import keras
from keras.models import Sequential  # step by step aaganor jonno
from keras.layers import Dense  # layer use korar jonno likes, input..hidden--> layer add korar jonno use hoy
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [4]:
data_set = pd.read_csv('iris.csv')
data_set

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
real_x = data_set.iloc[:,0:4].values # IV
real_y = data_set.iloc[:,4].values # DV/op

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(real_y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split # aage eta use hotw-->from sklearn.cross_validation import train_test_split
training_x,test_x,training_y,test_y = train_test_split(real_x,Y,test_size = 0.2, random_state=0)

In [8]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [10]:
model = Sequential()
model.add(Dense(4, input_shape = (4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [11]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(training_x, training_y, batch_size=10, nb_epoch=100)

Epoch 1/100
120/120 [==============================] - 0s 267us/step - loss: 0.3151 - accuracy: 0.9583
Epoch 2/100
120/120 [==============================] - 0s 133us/step - loss: 0.3132 - accuracy: 0.9583
Epoch 3/100
120/120 [==============================] - 0s 200us/step - loss: 0.3114 - accuracy: 0.9583
Epoch 4/100
120/120 [==============================] - 0s 267us/step - loss: 0.3095 - accuracy: 0.9583
Epoch 5/100
120/120 [==============================] - 0s 266us/step - loss: 0.3075 - accuracy: 0.9583
Epoch 6/100
120/120 [==============================] - 0s 200us/step - loss: 0.3056 - accuracy: 0.9583
Epoch 7/100
 10/120 [=>............................] - ETA: 0s - loss: 0.3348 - accuracy: 1.0000

C:\Users\Nayeem\.conda\envs\tensorflow 3_7\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


120/120 [==============================] - 0s 200us/step - loss: 0.3044 - accuracy: 0.9583
Epoch 8/100
120/120 [==============================] - 0s 200us/step - loss: 0.3019 - accuracy: 0.9583
Epoch 9/100
120/120 [==============================] - 0s 200us/step - loss: 0.3002 - accuracy: 0.9583
Epoch 10/100
120/120 [==============================] - 0s 267us/step - loss: 0.2986 - accuracy: 0.9583
Epoch 11/100
120/120 [==============================] - 0s 200us/step - loss: 0.2970 - accuracy: 0.9583
Epoch 12/100
120/120 [==============================] - 0s 333us/step - loss: 0.2951 - accuracy: 0.9583
Epoch 13/100
120/120 [==============================] - 0s 200us/step - loss: 0.2931 - accuracy: 0.9583
Epoch 14/100
120/120 [==============================] - 0s 200us/step - loss: 0.2917 - accuracy: 0.9583
Epoch 15/100
120/120 [==============================] - 0s 267us/step - loss: 0.2895 - accuracy: 0.9583
Epoch 16/100
120/120 [==============================] - 0s 267us/step - loss: 0

120/120 [==============================] - 0s 267us/step - loss: 0.1953 - accuracy: 0.9750
Epoch 86/100
120/120 [==============================] - 0s 267us/step - loss: 0.1945 - accuracy: 0.9667
Epoch 87/100
120/120 [==============================] - 0s 200us/step - loss: 0.1935 - accuracy: 0.9667
Epoch 88/100
120/120 [==============================] - 0s 200us/step - loss: 0.1930 - accuracy: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 200us/step - loss: 0.1919 - accuracy: 0.9750
Epoch 90/100
120/120 [==============================] - 0s 133us/step - loss: 0.1924 - accuracy: 0.9667
Epoch 91/100
120/120 [==============================] - 0s 200us/step - loss: 0.1897 - accuracy: 0.9667
Epoch 92/100
120/120 [==============================] - 0s 200us/step - loss: 0.1895 - accuracy: 0.9750
Epoch 93/100
120/120 [==============================] - 0s 200us/step - loss: 0.1876 - accuracy: 0.9750
Epoch 94/100
120/120 [==============================] - 0s 200us/step - loss:

In [13]:
# predicting the test result
y_pred = model.predict(test_x)
test_y_class = np.argmax(test_y,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [16]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(test_y_class,y_pred_class))
print(classification_report(test_y_class,y_pred_class))

[[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.00      0.00      0.00        13
           2       0.32      1.00      0.48         6

    accuracy                           0.57        30
   macro avg       0.44      0.67      0.49        30
weighted avg       0.43      0.57      0.46        30



C:\Users\Nayeem\.conda\envs\tensorflow 3_7\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
